cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/var/tmp/lena/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/var/tmp/lena/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 4147056876L: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'test.cpp.1.o\', \'-o\', \'/var/tmp/lena/build/.conf_check_968fbcee789046a8c143bb4a6e302895/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib64\', \'-lboost_system-mt\', \'-lboost_signals-mt\', \'-lboost_filesystem-mt\']\n'
